from openai import NOT_GIVEN

from agentlab.llm.chat_api import (
    AnthropicModelArgs,
    AzureModelArgs,
    BedrockModelArgs,
    FireworksModelArgs,
    OpenAIModelArgs,
    OpenRouterModelArgs,
    SelfHostedModelArgs,
)

default_oss_llms_args = {
    "n_retry_server": 4,
    "temperature": 0.01,
}

CLOSED_SOURCE_APIS = [
    "openai",
    "reka",
    "test",
]

CHAT_MODEL_ARGS_DICT = {
    "openai/gpt-4.1-mini-2025-04-14": OpenAIModelArgs(
        model_name="gpt-4.1-mini-2025-04-14",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=16_384,
        vision_support=True,
    ),
    "openai/gpt-4.1-2025-04-14": OpenAIModelArgs(
        model_name="gpt-4.1-2025-04-14",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=16_384,
        vision_support=True,
    ),
    "openai/o3-mini-2025-01-31": OpenAIModelArgs(
        model_name="o3-mini-2025-01-31",
        max_total_tokens=200_000,
        max_input_tokens=200_000,
        max_new_tokens=100_000,
        vision_support=False,
    ),
    "openai/o3-2025-04-16": OpenAIModelArgs(
        model_name="o3-2025-04-16",
        max_total_tokens=200_000,
        max_input_tokens=200_000,
        max_new_tokens=None,
        temperature=1,
        vision_support=True,
    ),
    "openai/gpt-4o-mini-2024-07-18": OpenAIModelArgs(
        model_name="gpt-4o-mini-2024-07-18",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=16_384,
        vision_support=True,
    ),
    "openai/gpt-4-1106-preview": OpenAIModelArgs(
        model_name="gpt-4-1106-preview",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=4_096,
    ),
    "openai/gpt-4-vision-preview": OpenAIModelArgs(
        model_name="gpt-4-vision-preview",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=16_384,  # I think this model has very small default value if we don't set max_new_tokens
        vision_support=True,
    ),
    "openai/gpt-4o-2024-05-13": OpenAIModelArgs(
        model_name="gpt-4o-2024-05-13",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=4_096,  # I think this model has very small default value if we don't set max_new_tokens
        vision_support=True,
    ),
    "openai/gpt-3.5-turbo-0125": OpenAIModelArgs(
        model_name="gpt-3.5-turbo-0125",
        max_total_tokens=16_384,
        max_input_tokens=16_384,
        max_new_tokens=4096,
    ),
    "openai/gpt-3.5-turbo-1106": OpenAIModelArgs(
        model_name="gpt-3.5-turbo-1106",
        max_total_tokens=16_384,
        max_input_tokens=16_384,
        max_new_tokens=4096,
    ),
    "openai/o1-mini": OpenAIModelArgs(
        model_name="openai/o1-mini",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=64_000,
        temperature=1e-1,
    ),
    "openai/gpt-4.1-nano-2025-04-14": OpenAIModelArgs(
        model_name="gpt-4.1-nano-2025-04-14",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=16_384,
        vision_support=True,
    ),
    "openai/gpt-5-nano-2025-08-07": OpenAIModelArgs(
        model_name="gpt-5-nano-2025-08-07",
        max_total_tokens=400_000,
        max_input_tokens=400_000 - 4_000,
        max_new_tokens=4_000,
        temperature=1,  # temperature param not supported by gpt-5
        vision_support=True,
    ),
    "openai/gpt-5-mini-2025-08-07": OpenAIModelArgs(
        model_name="gpt-5-mini-2025-08-07",
        max_total_tokens=400_000,
        max_input_tokens=400_000 - 4_000,
        max_new_tokens=4_000,
        temperature=1,  # temperature param not supported by gpt-5
        vision_support=True,
    ),
    "openai/gpt-5-2025-08-07": OpenAIModelArgs(
        model_name="gpt-5-2025-08-07",
        max_total_tokens=400_000,
        max_input_tokens=400_000 - 4_000,
        max_new_tokens=4_000,
        temperature=1,  # temperature param not supported by gpt-5
        vision_support=True,
    ),
    # ---------------- Azure ----------------#
    "azure/gpt-35-turbo/gpt-35-turbo": AzureModelArgs(
        model_name="gpt-35-turbo",
        max_total_tokens=8_192,
        max_input_tokens=7500,
        max_new_tokens=500,
    ),
    "azure/gpt-4o-2024-05-13": AzureModelArgs(
        model_name="gpt-4o",
        max_total_tokens=128_000,
        max_input_tokens=100_000,
        max_new_tokens=16_384,
        vision_support=True,
    ),
    "azure/gpt-4o-2024-08-06": AzureModelArgs(
        model_name="gpt-4o",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=16_384,
        vision_support=True,
    ),
    "azure/gpt-4o-mini-2024-07-18": AzureModelArgs(
        model_name="gpt-4o-mini",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=16_384,
        vision_support=True,
    ),
    "azure/gpt-4.1-2025-04-14": AzureModelArgs(
        model_name="gpt-4.1",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=16_384,
        vision_support=True,
    ),
    "azure/gpt-4.1-mini-2025-04-14": AzureModelArgs(
        model_name="gpt-4.1-mini",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=16_384,
        vision_support=True,
    ),
    "azure/gpt-4.1-nano-2025-04-14": AzureModelArgs(
        model_name="gpt-4.1-nano",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=16_384,
        vision_support=True,
    ),
    "azure/gpt-5-2025-08-07": AzureModelArgs(
        model_name="gpt-5",
        max_total_tokens=400_000,
        max_input_tokens=256_000,
        max_new_tokens=128_000,
        temperature=1,  # temperature param not supported by gpt-5
        vision_support=True,
    ),
    "azure/gpt-5-mini-2025-08-07": AzureModelArgs(
        model_name="gpt-5-mini",
        max_total_tokens=400_000,
        max_input_tokens=256_000,
        max_new_tokens=128_000,
        temperature=1,  # temperature param not supported by gpt-5
        vision_support=True,
    ),
    "azure/gpt-5-nano-2025-08-07": AzureModelArgs(
        model_name="gpt-5-nano",
        max_total_tokens=400_000,
        max_input_tokens=256_000,
        max_new_tokens=128_000,
        temperature=1,  # temperature param not supported by gpt-5
        vision_support=True,
    ),
    # ---------------- Anthropic ----------------#
    "anthropic/claude-3-7-sonnet-20250219": AnthropicModelArgs(
        model_name="claude-3-7-sonnet-20250219",
        max_new_tokens=16_384,
        temperature=1e-1,
    ),
    "anthropic/claude-sonnet-4-20250514": AnthropicModelArgs(
        model_name="claude-sonnet-4-20250514",
        max_new_tokens=16_384,
        temperature=1e-1,
    ),
    # ------------ Anthropic / Bedrock ------------#
    "bedrock/claude-3-7-sonnet": BedrockModelArgs(
        model_name="us.anthropic.claude-3-7-sonnet-20250219-v1:0",
        max_new_tokens=16_384,
        temperature=1e-1,
    ),
    "bedrock/claude-4-0-sonnet": BedrockModelArgs(
        model_name="us.anthropic.claude-sonnet-4-20250514-v1:0",
        max_new_tokens=16_384,
        temperature=1e-1,
    ),
    "bedrock/claude-4-5-sonnet": BedrockModelArgs(
        model_name="us.anthropic.claude-sonnet-4-5-20250929-v1:0",
        max_new_tokens=16_384,
        temperature=1e-1,
    ),
    # ---------------- OSS LLMs ----------------#
    "meta-llama/Meta-Llama-3-70B-Instruct": SelfHostedModelArgs(
        model_name="meta-llama/Meta-Llama-3-70B-Instruct",
        max_total_tokens=8_192,
        max_input_tokens=8_192 - 512,
        max_new_tokens=512,
        backend="huggingface",
        **default_oss_llms_args,
    ),
    "meta-llama/Meta-Llama-3-8B-Instruct": SelfHostedModelArgs(
        model_name="meta-llama/Meta-Llama-3-8B-Instruct",
        max_total_tokens=16_384,
        max_input_tokens=16_384 - 512,
        max_new_tokens=512,
        backend="huggingface",
        **default_oss_llms_args,
    ),
    "mistralai/Mixtral-8x22B-Instruct-v0.1": SelfHostedModelArgs(
        model_name="mistralai/Mixtral-8x22B-Instruct-v0.1",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        backend="huggingface",
        **default_oss_llms_args,
    ),
    # ---------------- OPENROUTER ----------------#
    "openrouter/deepseek/deepseek-r1": OpenRouterModelArgs(
        model_name="deepseek/deepseek-r1",
        max_total_tokens=128_000,
        max_input_tokens=100_000,
        max_new_tokens=128_000,
        temperature=1e-1,
    ),
    "openrouter/meta-llama/llama-3.1-405b-instruct": OpenRouterModelArgs(
        model_name="meta-llama/llama-3.1-405b-instruct",
        max_total_tokens=128_000,
        max_input_tokens=100_000,
        max_new_tokens=28_000,
        temperature=1e-1,
    ),
    "openrouter/meta-llama/llama-3.1-70b-instruct": OpenRouterModelArgs(
        model_name="meta-llama/llama-3.1-70b-instruct",
        max_total_tokens=128_000,
        max_input_tokens=100_000,
        max_new_tokens=28_000,
        temperature=1e-1,
    ),
    "openrouter/meta-llama/llama-3-70b-instruct": OpenRouterModelArgs(
        model_name="meta-llama/llama-3-70b-instruct",
        max_total_tokens=128_000,
        max_input_tokens=100_000,
        max_new_tokens=28_000,
        temperature=1e-1,
    ),
    "openrouter/meta-llama/llama-4-maverick": OpenRouterModelArgs(
        model_name="meta-llama/llama-4-maverick",
        max_total_tokens=128_000,
        max_input_tokens=100_000,
        max_new_tokens=28_000,
        temperature=1e-1,
        vision_support=True,
    ),
    "openrouter/meta-llama/llama-3.1-8b-instruct:free": OpenRouterModelArgs(
        model_name="meta-llama/llama-3.1-8b-instruct:free",
        max_total_tokens=128_000,
        max_input_tokens=100_000,
        max_new_tokens=28_000,
        temperature=1e-1,
    ),
    "openrouter/meta-llama/llama-3.1-8b-instruct": OpenRouterModelArgs(
        model_name="meta-llama/llama-3.1-8b-instruct",
        max_total_tokens=128_000,
        max_input_tokens=100_000,
        max_new_tokens=28_000,
        temperature=1e-1,
    ),
    "openrouter/anthropic/claude-3.5-sonnet:beta": OpenRouterModelArgs(
        model_name="anthropic/claude-3.5-sonnet:beta",
        max_total_tokens=200_000,
        max_input_tokens=200_000,
        max_new_tokens=8_192,
        temperature=1e-1,
        vision_support=True,
    ),
    "openrouter/qwen/qwen-2-72b-instruct": OpenRouterModelArgs(
        model_name="qwen/qwen-2-72b-instruct",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        temperature=1e-1,
    ),
    "openrouter/qwen/qwen3-8b": OpenRouterModelArgs(
        model_name="qwen/qwen3-8b",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        temperature=1e-1,
    ),
    "openrouter/qwen/qwen3-4b:free": OpenRouterModelArgs(
        model_name="qwen/qwen3-4b:free",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        temperature=1e-1,
    ),
    "openrouter/openai/gpt-4o-mini": OpenRouterModelArgs(
        model_name="openai/gpt-4o-mini",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=16_384,
        temperature=1e-1,
    ),
    # Fireworks AI models
    "fireworks/qwen3-4b": FireworksModelArgs(
        model_name="accounts/mapoout-86nt45w21bia/deployedModels/qwen3-4b-instruct-2507-g49te5fm",
        max_total_tokens=32_768,
        max_input_tokens=30_000,
        max_new_tokens=2_768,
        temperature=0.6,
    ),
    # Local vLLM models (set VLLM_API_URL env var, e.g. http://localhost:8000/v1)
    "vllm/qwen3-8b": SelfHostedModelArgs(
        model_name="Qwen/Qwen3-8B",
        max_total_tokens=16_000,
        max_input_tokens=14_000,
        max_new_tokens=2_000,
        temperature=0.6,
        backend="vllm",
    ),
    "vllm/qwen3-4b": SelfHostedModelArgs(
        model_name="Qwen/Qwen3-4B-Instruct-2507",
        max_total_tokens=8_192,
        max_input_tokens=6_000,
        max_new_tokens=2_192,
        temperature=0.6,
        backend="vllm",
    ),
    # Fine-tuned vLLM model (set VLLM_API_URL=http://localhost:8010/v1)
    "vllm/qwen3-4b-verienv-v0": SelfHostedModelArgs(
        model_name="qwen3-4b-verienv-v0",
        max_total_tokens=8_192,
        max_input_tokens=6_000,
        max_new_tokens=2_192,
        temperature=0.6,
        backend="vllm",
    ),
    # Fine-tuned vLLM model (served-model-name: qwen3-4b-verienv-0116)
    "vllm/qwen3-4b-verienv-0116": SelfHostedModelArgs(
        model_name="qwen3-4b-verienv-0116",
        max_total_tokens=16_000,
        max_input_tokens=14_000,
        max_new_tokens=2_000,
        temperature=0.6,
        backend="vllm",
    ),
    "vllm/qwen3-4b-instruct": SelfHostedModelArgs(
        model_name="qwen3-4b-instruct",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        temperature=1.0,
        backend="vllm",
        vllm_api_url="http://localhost:8002/v1",
    ),
    "vllm/qwen3-4b-wj-minstep3-ckpt800": SelfHostedModelArgs(
        model_name="qwen3-4b-wj-minstep3-ckpt800",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        temperature=1.0,
        backend="vllm",
        vllm_api_url="http://localhost:8000/v1",
    ),
    "vllm/qwen3-4b-wj-at-minstep3-ckpt2052": SelfHostedModelArgs(
        model_name="qwen3-4b-wj-at-minstep3-ckpt2052",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        temperature=1.0,
        backend="vllm",
        vllm_api_url="http://localhost:8001/v1",
    ),
    "vllm/qwen3-4b-verienv-0116-minstep3": SelfHostedModelArgs(
        model_name="qwen3-4b-minstep3",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        temperature=1.0,
        backend="vllm",
        vllm_api_url="http://localhost:8003/v1",
    ),
    "vllm/qwen3-4b-verienv-all-unfiltered": SelfHostedModelArgs(
        model_name="qwen3-4b-verienv-all-unfiltered",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        temperature=1.0,
        backend="vllm",
    ),
    "vllm/qwen3-4b-verienv-webjudge-filtered-action-tag-ckpt1200": SelfHostedModelArgs(
        model_name="qwen3-4b-verienv-webjudge-filtered-action-tag-ckpt1200",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        temperature=1.0,
        backend="vllm",
    ),
    "vllm/qwen3-4b-wj-final": SelfHostedModelArgs(
        model_name="qwen3-4b-wj-final",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        temperature=1.0,
        backend="vllm",
    ),
    "vllm/qwen3-4b-wj-ckpt1200": SelfHostedModelArgs(
        model_name="qwen3-4b-wj-ckpt1200",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        temperature=1.0,
        backend="vllm",
        vllm_api_url="http://localhost:8001/v1",
    ),
    "vllm/qwen3-4b-verienv-webjudge-filtered": SelfHostedModelArgs(
        model_name="qwen3-4b-verienv-webjudge-filtered",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        temperature=1.0,
        backend="vllm",
    ),
    "vllm/qwen3-4b-verienv-sdk-filtered": SelfHostedModelArgs(
        model_name="qwen3-4b-verienv-sdk-filtered",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        temperature=1.0,
        backend="vllm",
    ),
    "vllm/qwen3-4b-verienv-all-unfiltered-ckpt400": SelfHostedModelArgs(
        model_name="qwen3-4b-verienv-all-unfiltered-ckpt400",
        max_total_tokens=32_000,
        max_input_tokens=30_000,
        max_new_tokens=2_000,
        temperature=1.0,
        backend="vllm",
    ),
    "vllm/qwen3-4b-synatra": SelfHostedModelArgs(
        model_name="qwen3-4b-synatra",
        max_total_tokens=16_000,
        max_input_tokens=14_000,
        max_new_tokens=2_000,
        temperature=0.6,
        backend="vllm",
    ),
    "vllm/llama3.2-3b-verienv-0116-minstep": SelfHostedModelArgs(
        model_name="llama3.2-3b-verienv-0116-minstep",
        max_total_tokens=16_000,
        max_input_tokens=13_000,
        max_new_tokens=2_000,
        temperature=0.6,
        backend="vllm",
    ),
    "vllm/qwen3-4b-verienv-shopping": SelfHostedModelArgs(
        model_name="qwen3-4b-verienv-shopping",
        max_total_tokens=16_000,
        max_input_tokens=13_000,
        max_new_tokens=2_000,
        temperature=0.6,
        backend="vllm",
    ),
    "vllm/qwen3-4b-verienv-map-cont-400": SelfHostedModelArgs(
        model_name="qwen3-4b-verienv-map-cont-400",
        max_total_tokens=16_000,
        max_input_tokens=13_000,
        max_new_tokens=2_000,
        temperature=0.6,
        backend="vllm",
    ),
    "vllm/qwen3-4b-adp": SelfHostedModelArgs(
        model_name="qwen3-4b-adp",
        max_total_tokens=16_000,
        max_input_tokens=14_000,
        max_new_tokens=2_000,
        temperature=0.6,
        backend="vllm",
        vllm_api_url="http://localhost:8002/v1",
    ),
    "vllm/llama3.2-3b-instruct": SelfHostedModelArgs(
        model_name="meta-llama/Llama-3.2-3B-Instruct",
        max_total_tokens=16_000,
        max_input_tokens=14_000,
        max_new_tokens=2_000,
        temperature=0.6,
        backend="vllm",
    ),
    "vllm/llama3.2-3b": SelfHostedModelArgs(
        model_name="meta-llama/Llama-3.2-3B",
        max_total_tokens=16_000,
        max_input_tokens=14_000,
        max_new_tokens=2_000,
        temperature=0.6,
        backend="vllm",
    ),
    "vllm/llama3.2-3b-synatra": SelfHostedModelArgs(
        model_name="llama3.2-3b-synatra",
        max_total_tokens=16_000,
        max_input_tokens=14_000,
        max_new_tokens=2_000,
        temperature=0.6,
        backend="vllm",
    ),
    "vllm/llama3.2-3b-adp": SelfHostedModelArgs(
        model_name="llama3.2-3b-adp",
        max_total_tokens=16_000,
        max_input_tokens=14_000,
        max_new_tokens=2_000,
        temperature=0.6,
        backend="vllm",
    ),
    "vllm/qwen3-4b-map": SelfHostedModelArgs(
        model_name="qwen3-4b-map",
        max_total_tokens=16_000,
        max_input_tokens=14_000,
        max_new_tokens=2_000,
        temperature=0.6,
        backend="vllm",
    ),
    "vllm/qwen3-vl-4b": SelfHostedModelArgs(
        model_name="Qwen/Qwen3-VL-4B-Instruct",
        max_total_tokens=32_000,
        max_input_tokens=28_000,
        max_new_tokens=4_000,
        temperature=0.6,
        backend="vllm",
        vision_support=True,
    ),
    # WebJudge model (set VLLM_API_URL=http://localhost:8001/v1)
    "vllm/webjudge-7b": SelfHostedModelArgs(
        model_name="osunlp/WebJudge-7B",
        max_total_tokens=8_192,
        max_input_tokens=6_000,
        max_new_tokens=2_000,
        temperature=0.1,  # Low temperature for evaluation
        backend="vllm",
    ),
    "openrouter/anthropic/claude-3.7-sonnet": OpenRouterModelArgs(
        model_name="anthropic/claude-3.7-sonnet",
        max_total_tokens=18_000,
        max_input_tokens=16_000,
        max_new_tokens=2_000,
        temperature=1e-1,
        vision_support=True,
    ),
    "openrouter/openai/o1-mini-2024-09-12": OpenRouterModelArgs(
        model_name="openai/o1-mini-2024-09-12",
        max_total_tokens=128_000,
        max_input_tokens=128_000,
        max_new_tokens=64_000,
        temperature=1e-1,
    ),
    "openrouter/openai/gpt-oss-120b": OpenRouterModelArgs(
        model_name="openai/gpt-oss-120b",
        max_total_tokens=131_072,
        max_input_tokens=131_072 - 2000,
        max_new_tokens=2000,
        temperature=1e-1,
    ),
    "openrouter/openai/gpt-oss-20b": OpenRouterModelArgs(
        model_name="openai/gpt-oss-20b",
        max_total_tokens=131_072,
        max_input_tokens=131_072 - 2000,
        max_new_tokens=2000,
        temperature=1e-1,
    ),
    "openrouter/openai/gpt-5-nano": OpenRouterModelArgs(
        model_name="openai/gpt-5-nano",
        max_total_tokens=400_000,
        max_input_tokens=400_000 - 4_000,
        max_new_tokens=4_000,
        temperature=1e-1,
    ),
    "openrouter/openai/gpt-5-mini": OpenRouterModelArgs(
        model_name="openai/gpt-5-mini",
        max_total_tokens=400_000,
        max_input_tokens=400_000 - 4_000,
        max_new_tokens=4_000,
        temperature=1e-1,
    ),
    "openrouter/openai/gpt-5-chat": OpenRouterModelArgs(
        model_name="openai/gpt-5-chat",
        max_total_tokens=400_000,
        max_input_tokens=400_000 - 4_000,
        max_new_tokens=4_000,
        temperature=1e-1,
    ),
    "openrouter/openai/gpt-5.4": OpenRouterModelArgs(
        model_name="openai/gpt-5.4",
        max_total_tokens=400_000,
        max_input_tokens=400_000 - 4_000,
        max_new_tokens=4_000,
        temperature=1e-1,
        vision_support=True,
    ),
    "openrouter/openai/o3-mini": OpenRouterModelArgs(
        model_name="openai/o3-mini",
        max_total_tokens=200_000,
        max_input_tokens=100_000 - 4_000,
        max_new_tokens=4_000,
        temperature=1e-1,
    ),
    # Qwen3-VL-4B LoRA SoM merged model
    "vllm/qwen3-vl-4b-verienv-som": SelfHostedModelArgs(
        model_name="qwen3-vl-4b-verienv-som",
        max_total_tokens=32_000,
        max_input_tokens=28_000,
        max_new_tokens=4_000,
        temperature=0.6,
        backend="vllm",
        vision_support=True,
    ),
}
