"""add genre description

Revision ID: c798e9346a24
Revises: 7c69fa412e18
Create Date: 2026-01-08 00:11:47.924335

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c798e9346a24'
down_revision = '7c69fa412e18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genres', 'description')
    # ### end Alembic commands ###

